INSERT INTO aeropuerto VALUES
-- Afghanistan 1
("KBL", "Hamid Karzai International Airport", 1),
("HEA", "Herat International Airport", 1),
("KDH", "Kandahar International Airport", 1),
("MZR", "Mazar-e Sharif International Airport", 1),
-- Albania 2
("TIA", "Tirana International Airport Nënë Tereza", 2),
-- Algeria 3
("AZR", "Touat-Cheikh Sidi Mohamed Belkebir Airport", 3),
("ALG", "Houari Boumedienne Airport", 3),
("AAE", "Rabah Bitat Airport", 3),
("BLJ", "Batna Airport", 3),
("BJA", "Soummam Airport", 3),
("BSK", "Biskra Airport", 3),
("CFK", "Chlef International Airport", 3),
("CZL", "Mohamed Boudiaf Airport", 3),
("HME", "Oued Irara Airport", 3),
("GJL", "Jijel Ferhat Abbas Airport", 3),
("ORN", "Oran Es Senia Airport", 3),
("QSF", "Ain Arnat Airport", 3),
("TMR", "Tamanrasset Airport", 3),
("TLM", "Zenata Airport", 3),
-- American Samoa 4
("PPG", "Pago Pago International Airport", 4),
-- Angola 6
("LAD", "Quatro de Fevereiro Airport", 6),
("SSD", "Lubango Airport", 6),
-- Anguilla 7
("AXA", "Clayton J. Lloyd International Airport", 7),
-- Antigua and Barbuda 9
("ANU", "VC Bird International Airport", 9),
-- Argentina 10
("EZE", "Ministro Pistarini International Airport", 10),
("AEP", "Aeroparque Jorge Newbery", 10),
("COR", "Ingeniero Ambrosio L.V. Taravella International Airport", 10),
("MDZ", "Governor Francisco Gabrielli International Airport", 10),
("IGR", "Cataratas del Iguazú International Airport", 10),
("RES", "Resistencia International Airport", 10),
("RGL", "Piloto Civil N. Fernández International Airport", 10),
("BRC", "Teniente Luis Candelaria International Airport", 10),
("USH", "Ushuaia International Airport", 10),
-- Armenia 11
("EVN", "Zvartnots International Airport", 11),
("LWN", "Shirak Airport", 11),
-- Aruba 12
("AUA", "Queen Beatrix International Airport", 12),
-- Australia 13
("ADL", "Adelaide Airport", 13),
("BNE", "Brisbane Airport", 13),
("CNS", "Cairns Airport", 13),
("CBR", "Canberra Airport", 13),
("DRW", "Darwin International Airport", 13),
("OOL", "Gold Coast Airport", 13),
("HBA", "Hobart International Airport", 13),
("MEL", "Melbourne Airport", 13),
("PER", "Perth Airport", 13),
("PHE", "Port Hedland International Airport", 13),
("SYD", "Sydney Airport", 13),
("TSV", "Townsville International Airport", 13),
-- Austria 14
("GRZ", "Graz Airport", 14),
("KLU", "Klagenfurt Airport", 14),
("INN", "Innsbruck Airport", 14),
("LNZ", "Linz Airport", 14),
("SZG", "Salzburg Airport", 14),
("VIE", "Vienna International Airport", 14),
-- Azerbaijan 15
("GYD", "Heydar Aliyev International Airport", 15),
("KVD", "Ganja International Airport", 15),
("NAJ", "Nakhchivan Airport", 15),
("GBB", "Qabala International Airport", 15),
("LLK", "Lankaran International Airport", 15),
-- Bahamas 16
("NAS", "Lynden Pindling International Airport", 16),
("CCZ", "Chub Cay International Airport", 16),
("GGT", "Exuma International Airport", 16),
("FPO", "Grand Bahama International Airport", 16),
("RSD", "Rock Sound International Airport", 16),
("MHH", "Marsh Harbour International Airport", 16),
-- Bahrain 17
("BAH", "Bahrain International Airport", 17),
-- Bangladesh 18
("CGP", "Shah Amanat International Airport", 18),
("DAC", "Hazrat Shahjalal International Airport", 18),
("ZYL", "Osmani International Airport", 18),
-- Barbados 19
("BGI", "Grantley Adams International Airport", 19),
-- Belarus 20
("GNA", "Hrodna Airport", 20),
("GME", "Gomel Airport", 20),
("MSQ", "Minsk International Airport", 20),
-- Belgium 21
("ANR", "Antwerp International Airport", 21),
("BRU", "Brussels Airport", 21),
("CRL", "Brussels South Charleroi Airport", 21),
("LGG", "Liège Airport", 21),
("OST", "Ostend-Bruges International Airport", 21),
-- Belize 22
("BZE", "Philip S. W. Goldson International Airport", 22),
-- Benin 23
("COO", "Cadjehoun Airport", 23),
-- Bermuda 24
("BDA", "L.F. Wade International Airport", 24),
-- Bhutan 25
("PBH", "Paro Airport", 25),
-- Bolivia 26
("LPB", "El Alto International Airport", 26),
("VVI", "Viru Viru International Airport", 26),
-- Bosnia and Herzegovina 27
("BNX", "Banja Luka International Airport", 27),
("SJJ", "Sarajevo International Airport", 27),
("TZL", "Tuzla International Airport", 27),
("OMO", "Mostar International Airport", 27),
-- Botswana 28
("GBE", "Sir Seretse Khama International Airport", 28),
("MUB", "Maun Airport", 28),
("FRW", "Francistown Airport", 28),
("BBK", "Kasane Airport", 28),
-- Brazil 30
("AJU", "Santa Maria Airport", 30),
("BEL", "Val de Cães International Airport", 30),
("CNF", "Tancredo Neves International Airport", 30),
("BVB", "Boa Vista International Airport", 30),
("BSB", "Brasília International Airport", 30),
("VCP", "Viracopos International Airport", 30),
("CGR", "Campo Grande International Airport", 30),
("CGB", "Marechal Rondon International Airport", 30),
("CWB", "Afonso Pena International Airport", 30),
("FLN", "Hercílio Luz International Airport", 30),
("FOR", "Pinto Martins International Airport", 30),
("IGU", "Cataratas International Airport", 30),
("GYN", "Santa Genoveva Airport", 30),
("JPA", "Presidente Castro Pinto International Airport", 30),
("MCZ", "Zumbi dos Palmares International Airport", 30),
("MAO", "Eduardo Gomes International Airport", 30),
("NAT", "Greater Natal International Airport", 30),
("PNZ", "Senador Nilo Coelho Airport", 30),
("POA", "Salgado Filho International Airport", 30),
("PVH", "Governador Jorge Teixeira de Oliveira International Airport", 30),
("REC", "Guararapes International Airport", 30),
("RBR", "Rio Branco International Airport", 30),
("GIG", "Rio de Janeiro-Galeão International Airport", 30),
("SDU", "Santos Dumont Airport", 30),
("SSA", "Deputado Luís Eduardo Magalhães International Airport", 30),
("SLZ", "Marechal Cunha Machado International Airport", 30),
("CGH", "São Paulo–Congonhas Airport", 30),
("GRU", "São Paulo-Guarulhos International Airport", 30),
("THE", "Teresina Airport", 30),
("UDI", "Uberlândia Airport", 30),
("VIX", "Eurico de Aguiar Salles Airport", 30),
-- British Virgin Islands 32
("EIS", "Terrance B. Lettsome International Airport", 32),
-- Brunei Darussalam 33
("BWN", "Brunei International Airport", 33),
-- Bulgaria 34
("BOJ", "Burgas Airport", 34),
("PDV", "Plovdiv Airport", 34),
("SOF", "Sofia Airport", 34),
("VAR", "Varna Airport", 34),
-- Burkina Faso 35
("BOY", "Bobo Dioulasso Airport", 35),
("OUA", "Ouagadougou Airport", 35),
-- Burundi 36
("BJM", "Bujumbura International Airport", 36),
-- Cambodia 37
("PNH", "Phnom Penh International Airport", 37),
("REP", "Siem Reap International Airport", 37),
("KOS", "Sihanouk International Airport", 37),
-- Cameroon 38
("DLA", "Douala Airport", 38),
("NSI", "Nsimalen Airport", 38),
-- Canada 39
("YYC", "Calgary International Airport", 39),
("YEG", "Edmonton International Airport", 39),
("YQX", "Gander International Airport", 39),
("YHZ", "Halifax Stanfield International Airport", 39),
("YHM", "John C. Munro Hamilton International Airport", 39),
("YXU", "London International Airport", 39),
("YQM", "Greater Moncton International Airport", 39),
("YUL", "Montreal-Pierre Elliott Trudeau International Airport", 39),
("YOW", "Ottawa Macdonald-Cartier International Airport", 39),
("YQB", "Quebec/Jean Lesage International Airport", 39),
("YQR", "Regina International Airport", 39),
("YXE", "Saskatoon John G. Diefenbaker International Airport", 39),
("YYT", "St. John's International Airport", 39),
("YYZ", "Toronto Pearson International Airport", 39),
("YVR", "Vancouver International Airport", 39),
("YYJ", "Victoria International Airport", 39),
("YWG", "Winnipeg James Armstrong Richardson International Airport", 39),
-- Cape Verde 40
("BVC", "Aristides Pereira International Airport", 40),
("SID", "Amílcar Cabral International Airport", 40),
("RAI", "Nelson Mandela International Airport", 40),
("VXE", "Cesária Évora Airport", 40),
-- Cayman Islands 41
("CYB", "Charles Kirkconnell International Airport", 41),
("GCM", "Owen Roberts International Airport", 41),
-- Central African Republic 42
("BGF", "M'Poko International Airport", 42),
-- Chad 43
("NDJ", "N'Djamena International Airport", 43),
-- Chile 44
("ANF", "Cerro Moreno International Airport", 44),
("IPC", "Mataveri International Airport", 44),
("CCP", "Carriel Sur International Airport", 44),
("PMC", "El Tepual International Airport", 44),
("PUQ", "Presidente Carlos Ibáñez del Campo International Airport", 44),
("SCL", "Comodoro Arturo Merino Benítez International Airport", 44),
-- China 45
("BHY", "Beihai Fucheng Airport", 45),
("PEK", "Beijing Capital International Airport", 45),
("NAY", "Beijing Nanyuan Airport", 45),
("CGQ", "Changchun Longjia International Airport", 45),
("CSX", "Changsha Huanghua International Airport", 45),
("CZX", "Changzhou Benniu Airport", 45),
("CTU", "Chengdu Shuangliu International Airport", 45),
("CKG", "Chongqing Jiangbei International Airport", 45),
("DDG", "Dandong Langtou Airport", 45),
("DLC", "Dalian Zhoushuizi International Airport", 45),
("DNH", "Dunhuang Airport", 45),
("FOC", "Fuzhou Changle International Airport", 45),
("CAN", "Guangzhou Baiyun International Airport", 45),
("KWL", "Guilin Liangjiang International Airport", 45),
("KWE", "Guiyang Longdongbao Airport", 45),
("HAK", "Haikou Meilan International Airport", 45),
("HGH", "Hangzhou Xiaoshan International Airport", 45),
("HRB", "Harbin Taiping International Airport", 45),
("HFE", "Hefei Xinqiao International Airport", 45),
("HUZ", "Huizhou Pingtan Airport", 45),
("SWA", "Jieyang Chaoshan International Airport", 45),
("TNA", "Jinan Yaoqiang International Airport", 45),
("KMG", "Kunming Changshui International Airport", 45),
("LHW", "Lanzhou Zhongchuan International Airport", 45),
("LXA", "Lhasa Gonggar Airport", 45),
("LZH", "Liuzhou Bailian Airport", 45),
("LYA", "Luoyang Beijiao Airport", 45),
("MIG", "Mianyang Nanjiao Airport", 45),
("MDG", "Mudanjiang Airport", 45),
("KHN", "Nanchang Changbei International Airport", 45),
("NKG", "Nanjing Lukou International Airport", 45),
("NNG", "Nanning Wuxu International Airport", 45),
("NTG", "Nantong Xingdong Airport", 45),
("NGB", "Ningbo Lishe International Airport", 45),
("TAO", "Qingdao liuting International Airport", 45),
("JJN", "Quanzhou Jinjiang International Airport", 45),
("SYX", "Sanya Phoenix International Airport", 45),
("SHA", "Shanghai Hongqiao International Airport", 45),
("PVG", "Shanghai Pudong International Airport", 45),
("SHE", "Shenyang Taoxian International Airport", 45),
("SZX", "Shenzhen Bao'an International Airport", 45),
("SJW", "Shijiazhuang Zhengding International Airport", 45),
("WUX", "Sunan Shuofang International Airport", 45),
("TYN", "Taiyuan Wusu International Airport", 45),
("TSN", "Tianjin Binhai International Airport", 45),
("THQ", "Tianshui Airport", 45),
("URC", "Ürümqi Diwopu International Airport", 45),
("WEH", "Weihai International Airport", 45),
("WNZ", "Wenzhou Yongqiang Airport", 45),
("WUH", "Wuhan Tianhe International Airport", 45),
("XMN", "Xiamen Gaoqi International Airport", 45),
("XIY", "Xi'an Xianyang International Airport", 45),
("XFN", "Xiangyang Airport", 45),
("XNN", "Xining Caojiabao Airport", 45),
("XIC", "Xichang Qingshan Airport", 45),
("XUZ", "Xuzhou Guanyin Airport", 45),
("YNZ", "Yancheng Nanyang Airport", 45),
("YNJ", "Yanji Airport", 45),
("YNT", "Yantai Penglai International Airport", 45),
("INC", "Yinchuan Hedong International Airport", 45),
("DYG", "Zhangjiajie Hehua Airport", 45),
("YZY", "Zhangye Ganzhou Airport", 45),
("CGO", "Zhengzhou Xinzheng International Airport", 45),
("HSN", "Zhoushan Putuoshan Airport", 45),
("ZUH", "Zhuhai Jinwan Airport", 45),
-- Christmas Island 46
("XCH", "Christmas Island Airport", 46),
-- Cocos (Keeling) Islands 47
("CCK", "Cocos (Keeling) Islands Airport", 47),
-- Colombia 48
("AXM", "El Edén International Airport", 48),
("BAQ", "Ernesto Cortissoz International Airport", 48),
("BOG", "El Dorado International Airport", 48),
("BGA", "Palonegro International Airport", 48),
("CLO", "Alfonso Bonilla Aragon International Airport", 48),
("CTG", "Rafael Núñez International Airport", 48),
("CUC", "Camilo Daza International Airport", 48),
("LET", "Alfredo Vásquez Cobo International Airport", 48),
("MDE", "José María Córdova International Airport", 48),
("PEI", "Matecaña International Airport", 48),
("ADZ", "Gustavo Rojas Pinilla International Airport", 48),
("SMR", "Simón Bolívar International Airport", 48),
-- Comoros 49
("HAH", "Prince Said Ibrahim International Airport", 49),
-- Congo 50
("GOM", "Goma International Airport", 50),
("FIH", "N'djili Airport", 50),
("FKI", "Bangoka International Airport", 50),
("FBM", "Lubumbashi International Airport", 50),
("BZV", "Maya-Maya Airport", 50),
("PNR", "Pointe Noire Airport", 50),
-- Cook Islands 51
("RAR", "Rarotonga Airport", 51),
-- Costa Rica 52
("LIR", "Daniel Oduber Quirós International Airport", 52),
("SJO", "Juan Santamaría International Airport", 52),
-- Cote d'Ivoire 53
("ABJ", "Port Bouet Airport", 53),
-- Croatia 54
("DBV", "Dubrovnik Airport", 54),
-- here
("ZAG", "Franjo Tuđman Airport", 54),
("OSI", "Osijek Airport", 54),
("PUY", "Pula Airport", 54),
("RJK", "Rijeka Airport", 54),
("SPU", "Split Airport", 54),
("ZAD", "Zadar Airport", 54),
-- Cuba 55
("CMW", "Ignacio Agramonte International Airport", 55),
("CCC", "Jardines del Rey Airport", 55),
("CYO", "Vilo Acuña Airport", 55),
("CFG", "Jaime González Airport", 55),
("HAV", "José Martí International Airport", 55),
("HOG", "Frank País Airport", 55),
("SNU", "Abel Santa María Airport", 55),
("SCU", "Antonio Maceo Airport", 55),
("VRA", "Juan Gualberto Gómez Airport", 55),
-- Cyprus 56
("LCA", "Larnaca International Airport", 56),
("PFO", "Paphos International Airport", 56),
("ECN", "Ercan International Airport", 56),
-- Czech Republic 57
-- here
("BRQ", "Brno-Tuřany Airport", 57),
("KLV", "Karlovy Vary Airport", 57),
-- here
("OSR", "Leoš Janáček Ostrava Airport", 57),
("PRG", "Prague Václav Havel Airport", 57),
("PED", "Pardubice Airport", 57),
-- Denmark 58
("AAL", "Aalborg Airport", 58),
("AAR", "Aarhus Airport", 58),
("BLL", "Billund Airport", 58),
("CPH", "Copenhagen Airport", 58),
-- Djibouti 59
("JIB", "Djibouti–Ambouli International Airport", 59),
-- Dominica 60
("DOM", "Melville Hall Airport", 60),
-- Dominican Republic 61
("BRX", "María Montez International Airport", 61),
("LRM", "La Romana International Airport", 61),
("PUJ", "Punta Cana International Airport", 61),
("AZS", "Samaná El Catey International Airport", 61),
("POP", "Gregorio Luperón International Airport", 61),
("STI", "Cibao International Airport", 61),
("SDQ", "Las Américas International Airport", 61),
-- Ecuador 62
("CUE", "Mariscal Lamar International Airport", 62),
("ESM", "Carlos Concha Torres International Airport", 62),
("GYE", "José Joaquín de Olmedo International Airport", 62),
("ETR", "Santa Rosa International Airport", 62),
("MEC", "Eloy Alfaro International Airport", 62),
("UIO", "Mariscal Sucre International Airport", 62),
("TUA", "Teniente Coronel Luis a Mantilla International Airport", 62),
-- Egypt 63
("HBE", "Borg El Arab Airport", 63),
("ALY", "Alexandria International Airport", 63),
("ATZ", "Assiut Airport", 63),
("ASW", "Aswan International Airport", 63),
("CAI", "Cairo International Airport", 63),
("AAC", "El Arish International Airport", 63),
("DBB", "Al Alamain International Airport", 63),
("HRG", "Hurghada International Airport", 63),
("LXR", "Luxor International Airport", 63),
("RMF", "Marsa Alam International Airport", 63),
("MUH", "Mersa Matruh Airport", 63),
("SKV", "St. Catherine International Airport", 63),
("SSH", "Sharm el-Sheikh International Airport", 63),
("HMB", "Sohag International Airport", 63),
("TCP", "Taba International Airport", 63),
-- El Salvador 64
("SAL", "Monseñor Óscar Arnulfo Romero International Airport", 64),
-- Equatorial Guinea 65
("SSG", "Malabo International Airport", 65),
-- Eritrea 66
("ASM", "Asmara International Airport", 66),
-- Estonia 67
("TLL", "Lennart Meri Tallinn Airport", 67),
("TAY", "Tartu Airport", 67),
-- Ethiopia 68
("ADD", "Addis Ababa Bole International Airport", 68),
("DIR", "Aba Tenna Dejazmach Yilma International Airport", 68),
-- Falkland Islands (Malvinas) 69
("MPN", "RAF Mount Pleasant", 69),
-- Faroe Islands 70
("FAE", "Vágar Airport", 70),
-- Fiji 71
("NAN", "Nadi International Airport", 71),
("SUV", "Nausori International Airport", 71),
-- Finland 72
("MHQ", "Mariehamn Airport (Åland)", 72),
("HEL", "Helsinki-Vantaa Airport", 72),
("KTT", "Kittilä Airport", 72),
("KUO", "Kuopio Airport", 72),
("KAO", "Kuusamo Airport", 72),
("LPP", "Lappeenranta Airport", 72),
("OUL", "Oulu Airport", 72),
("RVN", "Rovaniemi Airport", 72),
("TMP", "Tampere-Pirkkala Airport", 72),
("TKU", "Turku Airport", 72),
("VAA", "Vaasa Airport", 72),
-- France 73
("AJA", "Campo dell'Oro Airport", 73),
("BIA", "Poretta Airport", 73),
("BVA", "Beauvais-Tillé Airport", 73),
("EGC", "Bergerac-Roumanière Airport", 73),
("BZR", "Béziers Cap d'Agde Airport", 73),
("BIQ", "Biarritz Airport", 73),
("BOD", "Mérignac Airport", 73),
("BES", "Brest Bretagne Airport", 73),
("CCF", "Salvaza Airport", 73),
("XCR", "Châlons Vatry Airport", 73),
("CMF", "Chambéry-Savoie Airport", 73),
("DNR", "Pleurtuit Airport", 73),
("FSC", "Figari Sud-Corse Airport", 73),
("GNB", "Grenoble-Isère Airport", 73),
("LRH", "Île de Ré Airport", 73),
("LIL", "Lille Lesquin Airport", 73),
("LIG", "Bellegarde Airport", 73),
("LYS", "Saint-Exupéry Airport", 73),
("MRS", "Provence Airport", 73),
("BSL", "Basel-Mulhouse-Freiburg Airport", 73),
("NTE", "Nantes Atlantique Airport", 73),
("NCE", "Côte d'Azur Airport", 73),
("FNI", "Garons Airport", 73),
("CDG", "Charles de Gaulle Airport", 73),
("ORY", "Orly Airport", 73),
("PUF", "Uzein Airport", 73),
("PGF", "Llabanère Airport", 73),
("PIS", "Biard Airport", 73),
("RDZ", "Marcillac Airport", 73),
("EBU", "Bouthéon Airport", 73),
("SXB", "Strasbourg Airport", 73),
("TLN", "Hyères Le Palyvestre Airport", 73),
("TLS", "Blagnac Airport", 73),
("TUF", "Tours Loire Valley Airport", 73),
-- French Guinea 74
("CAY", "Cayenne-Rochambeau Airport", 74),
-- French Polynesia 75
("PPT", "Faa'a International Airport", 75),
-- Gabon 77
("MVB", "M'Vengue El Hadj Omar Bongo Ondimba International Airport", 77),
("LBV", "Libreville International Airport", 77),
("POG", "Port-Gentil International Airport", 77),
-- Gambia 78
("BJL", "Banjul International Airport", 78),
-- Georgia 79
("UGAM", "Ambrolauri Airport", 79),
("BUS", "Batumi International Airport", 79),
("KUT", "Kutaisi International Airport", 79),
("UGMS", "Queen Tamar Airport", 79),
("UGSA", "Natakhtari Airfield", 79),
("SUI", "Sukhumi Babushara Airport", 79),
("TBS", "Tbilisi International Airport", 79),
-- Germany 80
("FKB", "Karlsruhe/Baden-Baden Airport", 80),
("TXL", "Berlin Tegel Airport", 80),
("SXF", "Berlin Schönefeld Airport", 80),
("BER", "Berlin Brandenburg Airport (Future)", 80),
("BRE", "Bremen Airport", 80),
("CGN", "Cologne/Bonn Airport", 80),
("DTM", "Dortmund Airport", 80),
("DUS", "Düsseldorf Airport", 80),
("FRA", "Frankfurt Airport", 80),
("HHN", "Frankfurt-Hahn Airport", 80),
("MLH", "EuroAirport Basel–Mulhouse–Freiburg", 80),
("FDH", "Friedrichshafen Airport", 80),
("HAM", "Hamburg Airport", 80),
("HAJ", "Langenhagen Airport", 80),
("LEJ", "Leipzig/Halle Airport", 80),
("LBC", "Lübeck Airport", 80),
("FMM", "Memmingen Airport", 80),
("MUC", "Munich Airport", 80),
("NUE", "Albrecht Dürer Airport", 80),
("STR", "Stuttgart Airport", 80),
("NRN", "Weeze Airport", 80),
-- Ghana 81
("ACC", "Kotoka International Airport", 81),
("TML", "Tamale Airport", 81),
-- Gibraltar 82
("GIB", "North Front Airport", 82),
-- Greece 83
("ATH", "Athens International Airport", 83),
("CHQ", "Chania International Airport", 83),
("JKH", "Chios Island National Airport", 83),
("CFU", "Ioannis Kapodistrias Airport", 83),
("HER", "Heraklion International Airport", 83),
("KLX", "Kalamata International Airport", 83),
("AOK", "Karpathos Island National Airport", 83),
("KVA", "Kavala International Airport", 83),
("EFL", "Kefalonia Island International Airport", 83),
("KGS", "Kos Island International Airport", 83),
("JMK", "Mykonos Island National Airport", 83),
("MJT", "Mytilene International Airport", 83),
("PVK", "Aktion National Airport", 83),
("RHO", "Rhodes International Airport", 83),
("SMI", "Samos International Airport", 83),
("JTR", "Santorini (Thira) National Airport", 83),
("JSI", "Skiathos Island National Airport", 83),
("SKU", "Skyros Island National Airport", 83),
("SKG", "Thessaloniki International Airport", 83),
("VOL", "Nea Anchialos National Airport", 83),
("ZTH", "Zakynthos International Airport", 83),
-- Greenland 84
("SFJ", "Kangerlussuaq Airport", 84),
("GOH", "Nuuk Airport", 84),
("JAV", "Ilulissat Airport", 84),
("UAK", "Narsarsuaq Airport", 84),
-- Grenada 85
("GND", "Maurice Bishop International Airport", 85),
-- Guadeloupe 86
("PTP", "Pôle Caraïbes International Airport", 86),
-- Guam 87
("GUM", "Antonio B. Won Pat International Airport", 87),
-- Guatemala 88
("FRS", "Mundo Maya International Airport", 88),
("GUA", "La Aurora International Airport", 88),
-- Guernsey 89
("GCI", "Guernsey Airport", 89),
-- Guinea 90
("CKY", "Conakry International Airport", 90),
-- Guinea-Bissau 91
("OXB", "Osvaldo Vieira International Airport", 91),
("BQE", "Bubaque Airport", 91),
-- Guyana 92
("GEO", "Cheddi Jagan International Airport", 92),
-- Haiti 93
("CAP", "Hugo Chávez International Airport", 93),
("PAP", "Toussaint Louverture International Airport", 93),
-- Honduras 96
("LCE", "Golosón International Airport", 96),
("RTB", "Juan Manuel Gálvez International Airport", 96),
("SAP", "Ramón Villeda Morales International Airport", 96),
("TGU", "Toncontin International Airport", 96),
-- Hong Kong 97
("HKG", "Hong Kong International Airport", 97),
-- Hungary 98
("BUD", "Budapest Ferenc Liszt International Airport", 98),
("DEB", "Debrecen International Airport", 98),
("SOB", "Hévíz-Balaton Airport", 98),
("QGY", "Győr-Pér International Airport", 98),
("QPJ", "Pécs-Pogány International Airport", 98),
-- Iceland 99
("AEY", "Akureyri Airport", 99),
("KEF", "Keflavik International Airport", 99),
("RKV", "Reykjavik Airport", 99),
-- India 100
("IXZ", "Veer Savarkar International Airport", 100),
("AMD", "Sardar Vallabhbhai Patel International Airport", 100),
("ATQ", "Sri Guru Ram Dass Jee International Airport", 100),
("BLR", "Kempegowda International Airport", 100),
("BHO", "Raja Bhoj International Airport", 100),
("BBI", "Biju Patnaik International Airport", 100),
("IXC", "Chandigarh International Airport", 100),
("MAA", "Chennai International Airport", 100),
("COK", "Cochin International Airport", 100),
("CJB", "Coimbatore International Airport", 100),
("DEL", "Indira Gandhi International Airport", 100),
("DHR", "Dholera International Airport", 100),
("GOI", "Goa International Airport", 100),
("MGI", "Mopa Airport", 100),
("GAY", "Gaya International Airport", 100),
("GAU", "Lokpriya Gopinath Bordoloi International Airport", 100),
("HYD", "Rajiv Gandhi International Airport", 100),
("IMF", "Imphal International Airport", 100),
("IDR", "Devi Ahilya Bai Holkar International Airport", 100),
("JAI", "Jaipur International Airport", 100),
("CNN", "Kannur International Airport", 100),
("CCU", "Netaji Subhash Chandra Bose International Airport", 100),
("CCJ", "Calicut International Airport", 100),
("SIA", "Sabarigiri International Airport", 100),
("LKO", "Chaudhary Charan Singh International Airport", 100),
("IXM", "Madurai International Airport", 100),
("IXE", "Mangalore International Airport", 100),
("BOM", "Chhatrapati Shivaji International Airport", 100),
("NAG", "Dr. Babasaheb Ambedkar International Airport", 100),
("KPR", "Captain Lakshmi Sehgal International Airport", 100),
("PAT", "Jay Prakash Narayan International Airport", 100),
("PNQ", "Pune International Airport", 100),
("CRA", "Chhatrapati Sambhaji Raje International Airport", 100),
("RPR", "Swami Vivekananda Airport", 100),
("IXR", "Birsa Munda International Airport", 100),
("IXB", "Bagdogra International Airport", 100),
("SXR", "Srinagar Airport", 100),
("TRZ", "Tiruchirappalli International Airport", 100),
("TIR", "Tirupati Airport", 100),
("TRV", "Trivandrum International Airport", 100),
("VNS", "Lal Bahadur Shastri International Airport", 100),
("VGA", "Vijayawada International Airport", 100),
("VTZ", "Visakhapatnam Airport", 100),
-- Indonesia 101
("UPG", "Hasanuddin International Airport", 101),
("MDC", "Sam Ratulangi International Airport", 101),
("LOP", "Lombok International Airport", 101),
("KNO", "Kuala Namu International Airport", 101),
("PDG", "Minangkabau International Airport", 101),
("PLM", "Sultan Mahmud Badaruddin II Airport", 101),
("PKU", "Sultan Syarif Qasim II International Airport", 101),
("SRI", "Samarinda International Airport", 101),
("SRG", "Achmad Yani International Airport", 101),
("SUB", "Juanda International Airport", 101),
("SOC", "Adisumarmo International Airport", 101),
("JOG", "Adisucipto International Airport", 101),
("CGK", "Soekarno Hatta International Airport", 101),
("HLP", "Halim Perdanakusuma International Airport", 101),
("DPS", "Ngurah Rai International Airport", 101),
("BDO", "Husein Sastranegara International Airport", 101),
("BPN", "Sultan Aji Muhammad Sulaiman Airport", 101),
("AMQ", "Pattimura Airport", 101),
("PKY", "Tjilik Riwut Airport", 101),
("DJJ", "Sentani Airport", 101),
("BDJ", "Syamsudin Noor Airport", 101),
("KOE", "El Tari Airport", 101),
("PLW", "Mutiara Airport", 101),
("KDI", "Haluoleo Airport", 101),
-- Iran 102
("BND", "Bandar Abbas International Airport", 102),
("XBJ", "Birjand International Airport", 102),
("IFN", "Isfahan International Airport", 102),
("KIH", "Kish Airport", 102),
("MHD", "Mashhad International Airport", 102),
("THR", "Mehrabad International Airport", 102),
("GSM", "Dayrestan Airport", 102),
("SYZ", "Shiraz International Airport", 102),
("TBZ", "Tabriz International Airport", 102),
("IKA", "Tehran Imam Khomeini International Airport", 102),
-- Iraq 103
("NJF", "Al Najaf International Airport", 103),
("BGW", "Baghdad International Airport", 103),
("BSR", "Basra International Airport", 103),
("EBL", "Erbil International Airport", 103),
("OSM", "Mosul International Airport", 103),
("ISU", "Sulaimaniyah International Airport", 103),
-- Ireland 104
("ORK", "Cork Airport", 104),
("DUB", "Dublin Airport", 104),
("KIR", "Kerry Airport", 104),
("NOC", "Ireland West Airport Knock", 104),
("SNN", "Shannon Airport", 104),
-- Isle of Man 105
("IOM", "Isle of Man Airport", 105),
-- Israel 106
("ETM", "Ramon Airport", 106),
("HFA", "Haifa Airport", 106),
("VDA", "Ovda International Airport", 106),
("TLV", "Ben Gurion Airport", 106),
-- Italy 107
("AHO", "Fertilia Airport", 107),
("AOI", "Ancona Airport", 107),
("BRI", "Palese Airport", 107),
("BGY", "Orio al Serio Airport", 107),
("BLQ", "Bologna Airport", 107),
("VBS", "Brescia Airport", 107),
("BDS", "Brindisi Airport", 107),
("CAG", "Cagliari Airport", 107),
("CTA", "Fontanarossa Airport", 107),
("CUF", "Cuneo Levaldigi Airport", 107),
("FLR", "Peretola Airport", 107),
("GOA", "Cristoforo Colombo Airport", 107),
("SUF", "Lamezia Terme Airport", 107),
("LIN", "Linate Airport", 107),
("MXP", "Malpensa Airport", 107),
("NAP", "Capodichino Airport", 107),
("OLB", "Costa Smeralda Airport", 107),
("PMO", "Palermo Airport", 107),
("PEG", "San Egidio Airport", 107),
("PSR", "Abruzzo Airport", 107),
("PSA", "Galileo Galilei Airport", 107),
("RMI", "Federico Fellini Airport", 107),
("FCO", "Leonardo da Vinci-Fiumicino Airport", 107),
("CIA", "Rome Ciampino Airport", 107),
("TPS", "Vincenzo Florio Airport", 107),
("TRS", "Friuli Venezia Giulia Airport", 107),
("TRN", "Caselle Airport", 107),
("VCE", "Venice Marco Polo Airport", 107),
("VRN", "Verona Airport", 107),
-- Jamaica 108
("KIN", "Norman Manley International Airport", 108),
("MBJ", "Sangster International Airport", 108),
-- Japan 109
("AXT", "Akita Airport", 109),
("AOJ", "Aomori Airport", 109),
("FUK", "Fukuoka Airport", 109),
("HKD", "Hakodate Airport", 109),
("KOJ", "Kagoshima Airport", 109),
("KMQ", "Komatsu Airport", 109),
("HIJ", "Hiroshima Airport", 109),
("KKJ", "New Kitakyushu Airport", 109),
("NGS", "Nagasaki Airport", 109),
("NGO", "Chubu Centrair International Airport", 109),
("KIJ", "Niigata Airport", 109),
("OIT", "Oita Airport", 109),
("OKJ", "Okayama Airport", 109),
("KIX", "Kansai International Airport", 109),
("CTS", "New Chitose Airport", 109),
("SDJ", "Sendai Airport", 109),
("FSZ", "Shizuoka Airport", 109),
("HND", "Haneda International Airport", 109),
("NRT", "Narita International Airport", 109),
-- Jersey 110
("JER", "Jersey Airport", 110),
-- Jordan 111
("AQJ", "King Hussein International Airport", 111),
("AMM", "Queen Alia International Airport", 111),
("ADJ", "Amman Civil Airport", 111),
-- Kazakhstan 112
("SCO", "Aktau Airport", 112),
("ALA", "Almaty International Airport", 112),
("TSE", "Astana International Airport", 112),
("GUW", "Atyrau Airport", 112),
("KGF", "Karaganda Airport", 112),
("KSN", "Kostanay Airport", 112),
("CIT", "Shymkent Airport", 112),
("URA", "Oral Ak Zhol Airport", 112),
-- Kenya 113
("EDL", "Eldoret International Airport", 113),
("MBA", "Moi International Airport", 113),
("KIS", "Kisumu International Airport", 113),
("NBO", "Jomo Kenyatta International Airport", 113),
-- Kiribati 114
("CXI", "Cassidy International Airport", 114),
("TRW", "Bonriki International Airport", 114),
-- Korea 115
("PUS", "Gimhae International Airport", 115),
("TAE", "Daegu Airport", 115),
("CJU", "Jeju International Airport", 115),
("GMP", "Gimpo International Airport", 115),
("ICN", "Incheon International Airport", 115),
("CJJ", "Cheongju International Airport", 115),
("MWX", "Muan International Airport", 115),
("YNY", "Yangyang International Airport", 115),
-- Kuwait 116
("KWI", "Kuwait International Airport", 116),
-- Kyrgyz Republic 117
("FRU", "Manas Airport", 117),
("OSS", "Osh Airport", 117),
-- Lao People's Democratic Republic 118
("LPQ", "Luang Prabang International Airport", 118),
("PKZ", "Pakse International Airport", 118),
("VTE", "Wattay International Airport", 118),
-- Latvia 119
("RIX",	"Riga International Airport", 119),
("VNT",	"Ventspils International Airport", 119),
-- Lebanon 120
("BEY", "Beirut Rafic Hariri International Airport", 120),
-- Lesotho 121
("MSU", "Moshoeshoe I International Airport", 121),
-- Liberia 122
("ROB", "Roberts International Airport", 122),
-- Libyan Arab Jamahiriya 123
("BEN", "Benina International Airport", 123),
("SEB", "Sebha Airport", 123),
("TIP", "Tripoli International Airport", 123),
("MJI", "Mitiga International Airport", 123),
-- Lithuania 125
("KUN", "Kaunas Airport", 125),
("PLQ", "Palanga International Airport", 125),
("SQQ", "Šiauliai International Airport", 125),
("VNO", "Vilnius International Airport", 125),
-- Luxembourg 126
("LUX", "Findel Airport", 126),
-- Macao 127
("MFM", "Macau International Airport", 127),
-- Macedonia 128
("OHD", "Ohrid St. Paul the Apostle Airport", 128),
("SKP", "Skopje Alexander the Great Airport", 128),
-- Madagascar 129
("TNR", "Ivato International Airport", 129),
("DIE", "Arrachart Airport", 129),
("MJN", "Amborovy Airport", 129),
("NOS", "Fascene Airport", 129),
("TMM", "Toamasina Airport", 129),
("FTU", "Tôlanaro Airport", 129),
("TLE", "Toliara Airport", 129),
-- Malawi 130
("BLZ", "Chileka International Airport", 130),
("LLW", "Lilongwe International Airport", 130),
-- Malaysia 131
("IPH", "Sultan Azlan Shah Airport", 131),
("JHB", "Senai International Airport", 131),
("KBR", "Sultan Ismail Petra Airport", 131),
("BKI", "Kota Kinabalu International Airport", 131),
("KUL", "Kuala Lumpur International Airport", 131),
("KCH", "Kuching International Airport", 131),
("LGK", "Langkawi International Airport", 131),
("PEN", "Penang International Airport", 131),
("SZB", "Sultan Abdul Aziz Shah Airport", 131),
-- Maldives 132
("MLE", "Velana International Airport", 132),
("GAN", "Gan International Airport", 132),
-- Mali 133
("BKO", "Senou International Airport", 133),
-- Malta 134
("MLA", "Malta International Airport", 134),
-- Marshall Islands 135
("KWA",	"Bucholz Army Airfield", 135),
("MAJ",	"Marshall Islands International Airport", 135),
-- Martinique 136
("FDF", "Martinique Aimé Césaire International Airport", 136),
-- Mauritania 137
("NKC", "Nouakchott–Oumtounsy International Airport", 137),
("NDB", "Nouadhibou International Airport", 137),
-- Mauritius 138
("MRU", "Sir Seewoosagur Ramgoolam International Airport", 138),
-- Mayotte 139
("DZA", "Dzaoudzi–Pamandzi International Airport", 139),
-- Mexico 140
("ACA", "General Juan N. Alvarez International Airport", 140),
("AGU", "Lic. Jesús Terán Peredo International Airport", 140),
("CUN", "Cancun International Airport", 140),
("CUU", "Roberto Fierro Villalobos International Airport", 140),
("CME", "Ciudad del Carmen International Airport", 140),
("CZM", "Cozumel International Airport", 140),
("CUL", "Federal de Bachigualato International Airport", 140),
("DGO", "General Guadalupe Victoria International Airport", 140),
("GDL", "Don Miguel Hidalgo y Costilla International Airport", 140),
("HMO", "Hermosillo International Airport", 140),
("HUX", "Bahías de Huatulco International Airport", 140),
("ZIH", "Ixtapa-Zihuatanejo International Airport", 140),
("BJX", "Del Bajío International Airport", 140),
("LTO", "Loreto International Airport", 140),
("SJD", "Los Cabos International Airport", 140),
("ZLO", "Playa de Oro International Airport", 140),
("MZT", "General Rafael Buelna International Airport", 140),
("MID", "Manuel Crescencio Rejón International Airport", 140),
("MEX", "Mexico City International Airport", 140),
("MTY", "General Mariano Escobedo International Airport", 140),
("MLM", "General Francisco J. Mujica International Airport", 140),
("OAX", "Xoxocotlán International Airport", 140),
("PBC", "Hermanos Serdán International Airport", 140),
("PVR", "Lic. Gustavo Díaz Ordaz International Airport", 140),
("QRO", "Querétaro Intercontinental Airport", 140),
("SLW", "Plan de Guadalupe International Airport", 140),
("SLP", "Ponciano Arriaga International Airport", 140),
("TAM", "General Francisco Javier Mina International Airport", 140),
("TIJ", "Gral. Abelardo L. Rodríguez International Airport", 140),
("TLC", "Lic. Adolfo López Mateos International Airport", 140),
("TRC", "Francisco Sarabia International Airport", 140),
("TGZ", "Angel Albino Corzo International Airport", 140),
("UPN", "Uruapan International Airport", 140),
("VER", "General Heriberto Jara International Airport", 140),
("VSA", "Carlos Rovirosa Pérez International Airport", 140),
("ZCL", "General Leobardo C. Ruiz International Airport", 140),
-- Micronesia 141
("TKK", "Chuuk International Airport", 141),
("KSA", "Kosrae International Airport", 141),
("PNI", "Pohnpei International Airport", 141),
("YAP", "Yap International Airport", 141),
-- Moldova 142
("KIV", "Chişinău International Airport", 142),
-- Mongolia 144
("ULN", "Chinggis Khaan International Airport", 144),
-- Montenegro 145
("TGD", "Podgorica Airport", 145),
("TIV", "Tivat Airport", 145),
-- Montserrat 146
("MNI", "John A. Osborne Airport", 146),
-- Morocco 147
("AGA", "Al Massira Airport", 147),
("CMN", "Mohammed V International Airport", 147),
("FEZ", "Fes-Saïss Airport", 147),
("RAK", "Marrakech-Menara Airport", 147),
("NDR", "Nador International Airport", 147),
("OUD", "Angads Airport", 147),
("RBA", "Rabat-Salé Airport", 147),
("TNG", "Tangier-Boukhalef Airport", 147),
("TTU", "Sania Ramel Airport", 147),
("VIL", "Dakhla Airport", 147),
("EUN", "Hassan I Airport", 147),
-- Mozambique 148
("MPM", "Maputo International Airport", 148),
("BEW", "Beira Airport", 148),
("INH", "Inhambane Airport", 148),
("APL", "Nampula Airport", 148),
("POL", "Pemba Airport", 148),
("TET", "Chingozi Airport", 148),
("VNX", "Vilankulo Airport", 148),
-- Myanmar 149
("MDL", "Mandalay International Airport", 149),
("RGN", "Yangon International Airport", 149),
("NYT", "Naypyidaw International Airport", 149),
-- Namibia 150
("WDH", "Hosea Kutako International Airport", 150),
("WVB", "Walvis Bay Airport", 150),
-- Nauru 151
("INU", "Nauru International Airport", 151),
-- Nepal 152
("KTM", "Tribhuvan International Airport", 152),
("BWA", "Gautam Buddha Airport", 152),
("PKR", "Pokhara International Airport", 152),
("NIJ", "Nijgadh International Airport", 152),
-- Netherlands 153
("AMS", "Amsterdam Airport Schiphol", 153),
("EIN", "Eindhoven Airport", 153),
("GRQ", "Groningen Airport Eelde", 153),
("MST", "Maastricht-Aachen Airport", 153),
("RTM", "Rotterdam The Hague Airport", 153),
-- New Caledonia 155
("NOU", "La Tontouta International Airport", 155),
-- New Zealand 156
("AKL", "Auckland Airport", 156),
("CHC", "Christchurch International Airport", 156),
("DUD", "Dunedin International Airport", 156),
("ZQN", "Queenstown Airport", 156),
("WLG", "Wellington International Airport", 156),
-- Nicaragua 157
("MGA", "Augusto C. Sandino International Airport", 157),
("BEF", "Bluefields Airport", 157),
("RNI", "Corn Island Airport", 157),
("PUZ", "Puerto Cabezas Airport", 157),
-- Niger 158
("NIM", "Diori Hamani International Airport", 158),
-- Nigeria 159
("ABV", "Nnamdi Azikiwe International Airport", 159),
("CBQ", "Margaret Ekpo International Airport", 159),
("ABB", "Asaba International Airport", 159),
("KAN", "Mallam Aminu Kano International Airport", 159),
("LOS", "Murtala Mohammed International Airport", 159),
("PHC", "Port Harcourt International Airport", 159),
("ENU", "Akanu Ibiam International Airport", 159),
("SKO", "Sadiq Abubakar III International Airport", 159),
-- Niue 160
("IUE", "Niue International Airport", 160),
-- Norfolk Island 161
("NLK", "Norfolk Airport", 161),
-- Northern Mariana Islands 162
("ROP", "Rota International Airport", 162),
("SPN", "Saipan International Airport", 162),
("TIQ", "Tinian International Airport", 162),
-- Norway 163
("AES", "Ålesund Airport", 163),
("BGO", "Bergen Airport", 163),
("BOO", "Bodø Airport", 163),
("HAU", "Haugesund Airport", 163),
("KRS", "Kristiansand Airport, Kjevik", 163),
("KSU", "Kristiansund Airport, Kvernberget", 163),
("OSL", "Oslo Airport-Gardermoen", 163),
("RYG", "Moss Airport", 163),
("TRF", "Sandefjord Airport", 163),
("SVG", "Stavanger Airport", 163),
("TOS", "Tromsø Airport", 163),
("TRD", "Trondheim Airport", 163),
-- Oman 164
("MCT", "Muscat International Airport", 164),
("SLL", "Salalah International Airport", 164),
-- Pakistan 165
("BHV", "Bahawalpur Airport", 165),
("BNP", "Bannu Airport", 165),
("CJL", "Chitral Airport", 165),
("DEA", "Dera Ghazi Khan International Airport", 165),
("DSK", "Dera Ismail Khan Airport", 165),
("LYP", "Faisalabad International Airport", 165),
("GIL", "Gilgit Airport", 165),
("GWD", "Gwadar International Airport", 165),
("ISB", "Benazir Bhutto International Airport", 165),
("KHI", "Jinnah International Airport", 165),
("OHT", "Kohat Airport", 165),
("LHE", "Allama Iqbal International Airport", 165),
("MUX", "Multan International Airport", 165),
("PEW", "Bacha Khan International Airport", 165),
("UET", "Quetta International Airport", 165),
("RYK", "Shaikh Zayed International Airport", 165),
("SDT", "Saidu Sharif Airport", 165),
("SKT", "Sialkot International Airport", 165),
("KDU", "Skardu Airport", 165),
("TUK", "Turbat International Airport", 165),
-- Palau 166
("ROR", "Roman Tmetuchl International Airport", 166),
-- Panama 168
("BOC", "Bocas del Toro 'Isla Colón' International Airport", 168),
("DAV", "Enrique Malek International Airport", 168),
("PTY", "Tocumen International Airport", 168),
-- Papua New Guinea 169
("POM", "Jacksons International Airport", 169),
-- Paraguay 170
("ASU", "Silvio Pettirossi International Airport", 170),
("AGT", "Guaraní International Airport", 170),
-- Peru 171
("AQP", "Rodríguez Ballón International Airport", 171),
("CUZ", "Alejandro Velasco Astete International Airport", 171),
("LIM", "Jorge Chávez International Airport", 171),
-- Philippines 172
("CEB", "Mactan–Cebu International Airport", 172),
("CRK", "Clark International Airport", 172),
("DVO", "Francisco Bangoy International Airport", 172),
("GES", "General Santos International Airport", 172),
("ILO", "Iloilo International Airport", 172),
("KLO", "Kalibo International Airport", 172),
("LAO", "Laoag International Airport", 172),
("MNL", "Ninoy Aquino International Airport", 172),
("TAG", "Bohol–Panglao International Airport", 172),
("PPS", "Puerto Princesa International Airport", 172),
("SFS", "Subic Bay International Airport", 172),
("ZAM", "Zamboanga International Airport", 172),
-- Poland 174
("BZG", "Bydgoszcz Ignacy Jan Paderewski Airport", 174),
("GDN", "Gdańsk Lech Wałęsa Airport", 174),
("KTW", "Katowice International Airport", 174),
("KRK", "John Paul II International Airport Kraków-Balice", 174),
("LUZ", "Lublin Airport", 174),
("LCJ", "Łódź Władysław Reymont Airport", 174),
("POZ", "Poznań Ławica Airport", 174),
("RZE", "Rzeszów-Jasionka Airport", 174),
("SZZ", "Szczecin-Goleniów 'Solidarność' Airport", 174),
("WAW", "Frédéric Chopin Airport", 174),
("WMI", "Modlin Airport", 174),
("WRO", "Copernicus Airport Wrocław", 174),
-- Portugal 175
("BYJ", "Beja Airport", 175),
("FAO", "Faro Airport", 175),
("FNC", "Madeira Airport", 175),
("PXO", "Porto Santo Airport", 175),
("LIS", "Humberto Delgado Airport", 175),
("OPO", "Francisco Sá Carneiro Airport", 175),
("PDL", "João Paulo II Airport", 175),
("TER", "Terceira Airport", 175),
-- Puerto Rico 176
("BQN", "Rafael Hernández Airport", 176),
("SJU", "Luis Muñoz Marín International Airport", 176),
-- Qatar 177
("DOH", "Hamad International Airport", 177),
-- Reunion 178
("RUN", "Roland Garros Airport", 178),
-- Romania 179
("OTP", "Henri Coanda International Airport", 179),
("CLJ", "Cluj-Napoca International Airport", 179),
("CND", "Mihail Kogălniceanu International Airport", 179),
("IAS", "Iași International Airport", 179),
("OMR", "Oradea International Airport", 179),
("SBZ", "Sibiu International Airport", 179),
("TSR", "Traian Vuia International Airport", 179),
-- Russian Federation 180
("ABA", "Abakan International Airport", 180),
("DYR", "Ugolny Airport", 180),
("AAQ", "Anapa Airport", 180),
("ARH", "Talagi Airport", 180),
("ASF", "Narimanovo Airport", 180),
("BAX", "Barnaul Airport", 180),
("EGO", "Belgorod International Airport", 180),
("BQS", "Ignatyevo Airport", 180),
("BTK", "Bratsk Airport", 180),
("BZK", "Bryansk International Airport", 180),
("CSY", "Cheboksary Airport", 180),
("CEK", "Chelyabinsk Airport", 180),
("CEE", "Cherepovets Airport", 180),
("HTA", "Kadala Airport", 180),
("ESL", "Elista Airport", 180),
("IKT", "Irkutsk Airport", 180),
("GRV", "Grozny Airport", 180),
("KGD", "Khrabrovo Airport", 180),
("KZN", "Kazan Airport", 180),
("KHV", "Khabarovsk Novy Airport", 180),
("KXK", "Komsomolsk-on-Amur Airport", 180),
("KRR", "Pashkovsky Airport", 180),
("KJA", "Yemelyanovo International Airport", 180),
("URS", "Kursk Vostochny Airport", 180),
("GDX", "Sokol Airport", 180),
("MQF", "Magnitogorsk International Airport", 180),
("MCX", "Uytash Airport", 180),
("MRV", "Mineralnye Vody Airport", 180),
("DME", "Domodedovo International Airport", 180),
("SVO", "Sheremetyevo International Airport", 180),
("VKO", "Vnukovo Airport", 180),
("MMK", "Murmansk Airport", 180),
("NAL", "Nalchik Airport", 180),
("NJC", "Nizhnevartovsk Airport", 180),
("NBC", "Begishevo Airport", 180),
("GOJ", "Strigino Airport", 180),
("NOZ", "Spichenkovo Airport", 180),
("OVB", "Tolmachevo Airport", 180),
("OMS", "Omsk Tsentralny Airport", 180),
("REN", "Orenburg Tsentralny Airport", 180),
("OSW", "Orsk Airport", 180),
("PEE", "Perm International Airport", 180),
("PES", "Petrozavodsk Airport", 180),
("PVS", "Provideniya Bay Airport", 180),
("PKC", "Yelizovo Airport", 180),
("PKV", "Pskov Airport", 180),
("ROV", "Rostov-na-Donu Airport", 180),
("LED", "Pulkovo Airport", 180),
("KUF", "Samara Kurumoch Airport", 180),
("RTW", "Saratov Tsentralny Airport", 180),
("AER", "Sochi International Airport", 180),
("STW", "Stavropol Shpakovskoye Airport", 180),
("SGC", "Surgut International Airport", 180),
("SCW", "Syktyvkar Airport", 180),
("TOF", "Bogashevo Airport", 180),
("TJM", "Roshchino International Airport", 180),
("UUD", "Baikal International Airport", 180),
("ULY", "Ulyanovsk Vostochny Airport", 180),
("UFA", "Ufa International Airport", 180),
("VVO", "Vladivostok International Airport", 180),
("OGZ", "Beslan Airport", 180),
("VOG", "Volgograd International Airport", 180),
("VOZ", "Voronezh International Airport", 180),
("YKS", "Yakutsk Airport", 180),
("IAR", "Tunoshna Airport", 180),
("SVX", "Koltsovo International Airport", 180),
("UUS", "Yuzhno-Sakhalinsk Airport", 180),
-- Rwanda 181
("KGL", "Kigali International Airport", 181),
-- Saint Barthelemy 182
("SBH", "Gustaf III Airport", 182),
-- Saint Helena 183
("HLE", "Saint Helena Airport", 183),
-- Saint Kitts and Nevis 184
("SKB", "Robert L. Bradshaw International Airport", 184),
-- Saint Lucia 185
("UVF", "Hewanorra International Airport", 185),
-- Saint Pierre and Miquelon 187
("FSP", "Saint-Pierre Airport", 187),
-- Saint Vincent and the Grenadines 188
("SVD", "Argyle International Airport", 188),
("CIW", "Canouan Airport", 188),
-- Samoa 189
("APW", "Faleolo International Airport", 189),
-- Sao Tome and Principe 191
("TMS", "São Tomé International Airport", 191),
-- Saudi Arabia 192
("DMM", "King Fahd International Airport", 192),
("JED", "King Abdulaziz International Airport", 192),
("MED", "Prince Mohammad Bin Abdulaziz International Airport", 192),
("RUH", "King Khalid International Airport", 192),
-- Senegal 193
("DKR", "Léopold Sédar Senghor International Airport", 193),
("DSS", "Blaise Diagne International Airport", 193),
-- Serbia 194
("BEG", "Belgrade Nikola Tesla Airport", 194),
("INI", "Niš Constantine the Great Airport", 194),
-- Seychelles 195
("SEZ", "Seychelles International Airport", 195),
-- Sierra Leone 196
("FNA", "Lungi International Airport", 196),
-- Singapore 197
("SIN", "Singapore Changi Airport", 197),
-- Slovakia (Slovak Republic) 198
("BTS", "M. R. Štefánik Airport", 198),
("KSC", "Košice International Airport", 198),
("PZY", "Piešťany Airport", 198),
("TAT", "Poprad-Tatry Airport", 198),
("SLD", "Sliač Airport", 198),
("ILZ", "Žilina Airport", 198),
-- Slovenia 199
("LJU", "Ljubljana Jože Pučnik Airport", 199),
("MBX", "Maribor Edvard Rusjan Airport", 199),
("POW", "Portorož Airport", 199),
-- Solomon Islands 200
("HIR", "Honiara International Airport", 200),
-- Somalia 201
("BSA", "Bosaso Airport", 201),
("GBY", "Abdullahi Yusuf Airport", 201),
("GGR", "Garowe Airport", 201),
("HGA", "Hargeisa Airport", 201),
("KMU", "Kismayo Airport", 201),
("MGQ", "Aden Adde International Airport", 201),
-- South Africa 202
("CPT", "Cape Town International Airport", 202),
("DUR", "King Shaka International Airport", 202),
("JNB", "OR Tambo International Airport", 202),
("MQP", "Kruger Mpumalanga International Airport", 202),
("HLA", "Lanseria International Airport", 202),
-- Spain 204
("LCG", "Alvedro Airport", 204),
("ALC", "Alicante Airport", 204),
("LEI", "Almería International Airport", 204),
("OVD", "Asturias Airport", 204),
("BCN", "Barcelona Airport", 204),
("FUE", "Fuerteventura Airport", 204),
("GRO", "Girona-Costa Brava Airport", 204),
("LPA", "Gran Canaria Airport", 204),
("GRX", "Granada Airport", 204),
("HSK", "Huesca-Pirineos Airport", 204),
("IBZ", "Ibiza Airport", 204),
("XRY", "Jerez Airport", 204),
("SPC", "La Palma Airport", 204),
("ACE", "Lanzarote Airport", 204),
("ILD", "Alguaire Airport", 204),
("MAD", "Madrid-Barajas Airport", 204),
("AGP", "Málaga Airport", 204),
("MAH", "Menorca Airport", 204),
("MJV", "Murcia-San Javier Airport", 204),
("PMI", "Palma de Mallorca Airport", 204),
("REU", "Reus Airport", 204),
("SDR", "Santander Airport", 204),
("SCQ", "Santiago de Compostela Airport", 204),
("SVQ", "Seville Airport", 204),
("TFN", "Tenerife North Airport", 204),
("TFS", "Tenerife South Airport", 204),
("VLC", "Valencia Airport", 204),
("VLL", "Valladolid Airport", 204),
("ZAZ", "Zaragoza Airport", 204),
-- Sri Lanka 205
("CMB", "Bandaranaike International Airport", 205),
("HRi", "Mattala Rajapaksa International Airport", 205),
-- Sudan 206
("KRT", "Khartoum International Airport", 206),
("PZU", "Port Sudan New International Airport", 206),
-- Suriname 207
("PBM", "Johan Adolf Pengel International Airport", 207),
-- Swaziland 209
("SHO", "King Mswati III International Airport", 209),
-- Sweden 210
("GSE", "Gothenburg City Airport", 210),
("GOT", "Göteborg Landvetter Airport", 210),
("LLA", "Luleå Airport", 210),
("MMX", "Malmö Airport", 210),
("NRK", "Norrköping Airport", 210),
("OSD", "Åre Östersund Airport", 210),
("ARN", "Stockholm-Arlanda Airport", 210),
("BMA", "Stockholm-Bromma Airport", 210),
("NYO", "Stockholm-Skavsta Airport", 210),
("VST", "Stockholm-Västerås Airport", 210),
("UME", "Umeå Airport", 210),
("VXO", "Växjö Airport", 210),
("VBY", "Visby Airport", 210),
-- Switzerland 211
("BRN", "Bern-Belp Airport", 211),
("GVA", "Geneva International Airport", 211),
("ACH", "St. Gallen-Altenrhein Airport", 211),
("ZRH", "Zurich Airport", 211),
-- Syrian Arab Republic 212
("ALP", "Aleppo International Airport", 212),
("DAM", "Damascus International Airport", 212),
("LTK", "Bassel Al-Assad International Airport", 212),
-- Taiwan 213
("KHH", "Kaohsiung International Airport", 213),
("RMQ", "Taichung International Airport", 213),
("TSA", "Taipei Songshan Airport", 213),
("TPE", "Taoyuan International Airport", 213),
-- Tajikistan 214
("DYU", "Dushanbe Airport", 214),
("LBD", "Khujand Airport", 214),
-- Tanzania 215
("DAR", "Julius Nyerere International Airport", 215),
("JRO", "Kilimanjaro International Airport", 215),
("ZNZ", "Abeid Amani Karume International Airport", 215),
-- Thailand 216
("BKK", "Suvarnabhumi Airport", 216),
("DMK", "Don Mueang International Airport", 216),
("CNX", "Chiang Mai International Airport", 216),
("CEI", "Mae Fah Luang International Airport", 216),
("UTP", "U-Tapao International Airport", 216),
("HDY", "Hat Yai International Airport", 216),
("KBV", "Krabi International Airport", 216),
("HKT", "Phuket International Airport", 216),
("URT", "Surat Thani Airport", 216),
("USM", "Samui Airport", 216),
("UTH", "Udon Thani International Airport", 216),
-- Timor-Leste 217
("DIL", "Presidente Nicolau Lobato International Airport", 217),
-- Togo 218
("LFW", "Tokoin Airport", 218),
-- Tonga 220
("TBU", "Fuaʻamotu International Airport", 220),
("VAV", "Vava'u International Airport", 220),
-- Trinidad and Tobago 221
("POS", "Piarco International Airport", 221),
("TAB", "Arthur Napoleon Raymond Robinson International Airport", 221),
-- Tunisia 222
("DJE", "Zarzis Airport", 222),
("NBE", "Enfidha-Hammamet International Airport", 222),
("MIR", "Habib Bourguiba International Airport", 222),
("SFA", "Thyna International Airport", 222),
("TBJ", "Tabarka–Aïn Draham International Airport", 222),
("TOE", "Nefta International Airport", 222),
("TUN", "Carthage International Airport", 222),
-- Turkey 223
("ADA", "Şakirpaşa Airport", 223),
("ESB", "Esenboğa International Airport", 223),
("AYT", "Antalya Airport", 223),
("BJV", "Milas-Bodrum Airport", 223),
("YEI", "Yenişehir Airport", 223),
("DLM", "Dalaman Airport", 223),
("GZT", "Oğuzeli Airport", 223),
("IST", "Atatürk International Airport", 223),
("SAW", "Sabiha Gökçen International Airport", 223),
("ADB", "Adnan Menderes Airport", 223),
("ASR", "Erkilet Airport", 223),
("KYA", "Konya Airport", 223),
("KZR", "Zafer Airport", 223),
("MLX", "Erhaç Airport", 223),
("NAV", "Kapadokya Airport", 223),
("SZF", "Samsun-Çarşamba Airport", 223),
("TZX", "Trabzon Airport", 223),
("ONQ", "Zonguldak Airport", 223),
-- Turkmenistan 224
("ASB",	"Ashgabat Airport", 224),
("MYP",	"Mary International Airport", 224),
("KRW",	"Turkmenbashi International Airport", 224),
-- Turks and Caicos Islands 225
("PLS", "Providenciales Airport", 225),
-- Tuvalu 226
("FUN", "Funafuti International Airport", 226),
-- Uganda 227
("EBB", "Entebbe International Airport", 227),
-- Ukraine 228
("KBP", "Boryspil International Airport", 228),
("CWC", "Chernivtsi International Airport", 228),
("DOK", "Donetsk Airport", 228),
("DNK", "Dnipropetrovsk International Airport", 228),
("GML", "Gostomel Airport (cargo only, serving Kiev)", 228),
("IFO", "Ivano-Frankivsk International Airport", 228),
("HRK", "Kharkiv International Airport", 228),
("KWG", "Kryvyi Rih International Airport", 228),
("IEV", "Kyiv Zhuliany International Airport", 228),
("VSG", "Luhansk International Airport", 228),
("LWO", "Lviv Danylo Halytskyi International Airport", 228),
("NLV", "Mykolaiv International Airport", 228),
("ODS", "Odessa International Airport", 228),
("SIP", "Simferopol International Airport", 228),
("OZH", "Zaporizhia International Airport", 228),
-- United Arab Emirates 229
("AUH", "Abu Dhabi International Airport", 229),
("AAN", "Al Ain International Airport", 229),
("DWC", "Al-Maktoum International Airport", 229),
("DXB", "Dubai International Airport", 229),
("RKT", "Ras Al Khaimah International Airport", 229),
("SHJ", "Sharjah International Airport", 229),
-- United Kingdom 230
("BHX", "Birmingham International Airport", 230),
("BOH", "Bournemouth Airport", 230),
("BRS", "Bristol Airport", 230),
("CWL", "Cardiff Airport", 230),
("DSA", "Robin Hood Airport Doncaster Sheffield", 230),
("MME", "Durham Tees Valley Airport", 230),
("EMA", "East Midlands Airport", 230),
("EXT", "Exeter International Airport", 230),
("LBA", "Leeds Bradford International Airport", 230),
("LPL", "Liverpool John Lennon Airport", 230),
("LCY", "London City Airport", 230),
("LGW", "Gatwick Airport", 230),
("LHR", "Heathrow Airport", 230),
("LTN", "Luton Airport", 230),
("SEN", "Southend Airport", 230),
("STN", "Stansted Airport", 230),
("MAN", "Manchester Airport", 230),
("NCL", "Newcastle Airport", 230),
("NQY", "Newquay Cornwall Airport", 230),
("NWI", "Norwich International Airport", 230),
("SOU", "Southampton Airport", 230),
("ABZ", "Aberdeen Airport", 230),
("EDI", "Edinburgh Airport", 230),
("GLA", "Glasgow International Airport", 230),
("PIK", "Glasgow Prestwick Airport", 230),
("INV", "Inverness Airport", 230),
("BFS", "Belfast International Airport", 230),
("BHD", "George Best Belfast City Airport", 230),
("LDY", "City of Derry Airport", 230),
-- United States of America 232
("CAK", "Akron–Canton Airport", 232),
("AKC", "Akron Fulton International Airport", 232),
("ALB", "Albany International Airport", 232),
("ABQ", "Albuquerque International Sunport", 232),
("ANC", "Ted Stevens Anchorage International Airport", 232),
("ATW", "Appleton International Airport", 232),
("ATL", "Hartsfield-Jackson Atlanta International Airport", 232),
("ACY", "Atlantic City International Airport", 232),
("AUS", "Austin-Bergstrom International Airport", 232),
("BWI", "Baltimore-Washington International Thurgood Marshall Airport", 232),
("BGR", "Bangor International Airport", 232),
("BHM", "Birmingham-Shuttlesworth International Airport", 232),
("BOS", "Logan International Airport", 232),
("BUF", "Buffalo Niagara International Airport", 232),
("CLT", "Charlotte/Douglas International Airport", 232),
("CHS", "Charleston International Airport", 232),
("MDW", "Chicago Midway International Airport", 232),
("ORD", "O'Hare International Airport", 232),
("CVG", "Cincinnati/Northern Kentucky International Airport", 232),
("CLE", "Cleveland Hopkins International Airport", 232),
("CMH", "John Glenn Columbus International Airport", 232),
("LCK", "Rickenbacker International Airport", 232),
("DFW", "Dallas/Fort Worth International Airport", 232),
("DAY", "Dayton International Airport", 232),
("DEN", "Denver International Airport", 232),
("DSM", "Des Moines International Airport", 232),
("DTW", "Detroit Metropolitan Wayne County Airport", 232),
("FAI", "Fairbanks International Airport", 232),
("FLL", "Fort Lauderdale-Hollywood International Airport", 232),
("RSW", "Southwest Florida International Airport", 232),
("FAT", "Fresno Yosemite International Airport", 232),
("BDL", "Bradley International Airport", 232),
("GRB", "Green Bay–Austin Straubel International Airport", 232),
("ITO", "Hilo International Airport", 232),
("HNL", "Daniel K. Inouye International Airport", 232),
("IAH", "George Bush Intercontinental Airport", 232),
("HOU", "William P. Hobby Airport", 232),
("HSV", "Huntsville International Airport", 232),
("IND", "Indianapolis International Airport", 232),
("JAX", "Jacksonville International Airport", 232),
("JNU", "Juneau International Airport", 232),
("MCI", "Kansas City International Airport", 232),
("KTN", "Ketchikan International Airport", 232),
("EYW", "Key West International Airport", 232),
("KOA", "Kona International Airport", 232),
("LAL", "Lakeland Linder International Airport", 232),
("LAN", "Capital Region International Airport", 232),
("LAS", "McCarran International Airport", 232),
("LAX", "Los Angeles International Airport", 232),
("SDF", "Louisville International Airport", 232),
("MLB", "Melbourne International Airport", 232),
("MEM", "Memphis International Airport", 232),
("MIA", "Miami International Airport", 232),
("MKE", "General Mitchell International Airport", 232),
("MSP", "Minneapolis-Saint Paul International Airport", 232),
("MYR", "Myrtle Beach International Airport", 232),
("BNA", "Nashville International Airport", 232),
("MSY", "Louis Armstrong New Orleans International Airport", 232),
("JFK", "John F. Kennedy International Airport", 232),
("LGA", "LaGuardia Airport", 232),
("EWR", "Newark Liberty International Airport", 232),
("SWF", "Stewart International Airport", 232),
("OAK", "Metropolitan Oakland International Airport", 232),
("OMA", "Eppley Airfield", 232),
("ONT", "Ontario International Airport", 232),
("SNA", "John Wayne Airport", 232),
("MCO", "Orlando International Airport", 232),
("SFB", "Orlando Sanford International Airport", 232),
("PSP", "Palm Springs International Airport", 232),
("ECP", "Northwest Florida Beaches International Airport", 232),
("PNS", "Pensacola International Airport", 232),
("PHL", "Philadelphia International Airport", 232),
("PHX", "Phoenix Sky Harbor International Airport", 232),
("AZA", "Phoenix–Mesa Gateway Airport", 232),
("PIT", "Pittsburgh International Airport", 232),
("PWM", "Portland International Jetport", 232),
("PDX", "Portland International Airport", 232),
("PVD", "T.F. Green Airport", 232),
("RDU", "Raleigh-Durham International Airport", 232),
("RNO", "Reno-Tahoe International Airport", 232),
("ROC", "Greater Rochester International Airport", 232),
("RST", "Rochester International Airport", 232),
("RFD", "Chicago Rockford International Airport", 232),
("SMF", "Sacramento International Airport", 232),
("SLC", "Salt Lake City International Airport", 232),
("SAT", "San Antonio International Airport", 232),
("SBD", "San Bernardino International Airport", 232),
("SAN", "San Diego International Airport", 232),
("SFO", "San Francisco International Airport", 232),
("SJC", "San Jose International Airport", 232),
("SRQ", "Sarasota-Bradenton International Airport", 232),
("LKE", "Kenmore Air Harbor Seaplane Base", 232),
("BFI", "King County International Airport", 232),
("SEA", "Seattle-Tacoma International Airport", 232),
("PAE", "Paine Field", 232),
("GEG", "Spokane International Airport", 232),
("STL", "Lambert-Saint Louis International Airport", 232),
("PIE", "St. Petersburg-Clearwater International Airport", 232),
("SYR", "Syracuse Hancock International Airport", 232),
("TLH", "Tallahassee International Airport", 232),
("TPA", "Tampa International Airport", 232),
("DCA", "Ronald Reagan Washington National Airport**", 232),
("IAD", "Washington Dulles International Airport", 232),
("PBI", "Palm Beach International Airport", 232),
-- United States Virgin Islands 233
("STT", "Cyril E. King Airport", 233),
("STX", "Henry E. Rohlsen Airport", 233),
-- Uruguay 234
("MVD", "Carrasco International Airport", 234),
("PDP", "Capitan Corbeta CA Curbelo International Airport", 234),
-- Uzbekistan 235
("NMA", "Namangan Airport", 235),
("TAS", "Tashkent International Airport", 235),
-- Vanuatu 236
("SON", "Santo-Pekoa International Airport", 236),
("VLI", "Bauerfield International Airport", 236),
-- Venezuela 237
("CCS", "Simón Bolívar International Airport", 237),
("MAR", "La Chinita International Airport", 237),
("VLN", "Arturo Michelena International Airport", 237),
-- Vietnam 238
("DAD", "Da Nang International Airport", 238),
("HAN", "Noi Bai International Airport", 238),
("SGN", "Tan Son Nhat International Airport", 238),
("VCA", "Can Tho International Airport", 238),
("HPH", "Cat Bi International Airport", 238),
("HUI", "Phu Bai International Airport", 238),
("PQC", "Phu Quoc International Airport", 238),
("CXR", "Cam Ranh International Airport", 238),
("VCL", "Chu Lai International Airport", 238),
-- Wallis and Futuna 239
("FUT", "Pointe Vele Airport", 239),
("WLS", "Hihifo Airport", 239),
-- Yemen 241
("ADE", "Aden International Airport", 241),
("SAH", "Sana'a International Airport", 241),
("GXF", "Seiyun Airport", 241),
-- Zambia 242
("LVI", "Harry Mwanga Nkumbula International Airport", 242),
("LUN", "Kenneth Kaunda International Airport", 242),
("NLA", "Simon Mwansa Kapwepwe International Airport", 242),
-- Zimbabwe 243
("HRE", "Robert Gabriel Mugabe International Airport", 243),
("VFA", "Victoria Falls Airport", 243),
("BUQ", "Joshua Mqabuko Nkomo International Airport", 243);
